print (" \"Hi!\" ")
print (" \'Hello!\' ")
print (" \\MEET\\Module1\\")
print ("first \n second")
print ("no tab \t tab")
print("Instructor Alex asks, \"What are you learning today?\" \n The students reply, \'We are learning how to print!\' We can type print (“\\Day1\\”) to print out \Day1\.")
